Repository wp-cli/embed-command, pull requests merged in 2019-04, with the labels that each got.

#50 Modify tests to correctly verify `--force-regex` flag
  features/provider.feature
Labels: bug, scope:testing

#48 Apply PHPCS `WP_CLI_CS` rules
  embed-command.php
  src/Cache_Command.php
  src/Fetch_Command.php
  src/Handler_Command.php
  src/Provider_Command.php
Labels: scope:testing

#47 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  phpcs.xml.dist
Labels: scope:testing

#44 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#46 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:distribution

#51 Update README.md file
  README.md
Labels: scope:documentation
